import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/reusable/Header";
import MainContent from "@/components/reusable/MainContent";
import HeaderFilter from "@/components/dashboard/HeaderFilter";
import MainContextProvider from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "112 | WFM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body className={`${inter.className} bg-bg_color dark:bg-main_dark`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainContextProvider>
            <Header>
              <HeaderFilter />
            </Header>
            <MainContent>{children}</MainContent>
          </MainContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
